apiVersion: v1
kind: Service
metadata:
  name: brightlizard-otus-k8s-app-postgres-nodeport
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: brightlizard-otus-k8s-app-service-postgres
spec:
  selector:
    app: postgres
  type: CLusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432