apiVersion: v1
kind: ConfigMap
metadata:
  name: brightlizard-otus-k8s-app-config
data:
  # property-like keys; each key maps to a simple value
  spring.datasource.url: jdbc:postgresql://brightlizard-otus-k8s-app-service-postgres.otus.svc.cluster.local:5432/otus
  logging.level.net.brightlizard: DEBUG

  # file-like keys
  init.sql: |
    DROP TABLE IF EXISTS public.users;
    CREATE TABLE IF NOT EXISTS public.users (
        id VARCHAR PRIMARY KEY,
        username VARCHAR NOT NULL,
        firstName VARCHAR NOT NULL,
        lastName VARCHAR NOT NULL,
        email VARCHAR NOT NULL,
        phone VARCHAR NOT NULL,
        UNIQUE (username, email)
    )