server:
  port: 8000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    net.brightlizard: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://10.104.80.172:5432/otus
    username: postgres2
    password: postgres2
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    initialization-mode: always
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
  sql:
    init:
      mode: always
      schema-locations: db/init.sql


management:
  endpoints:
    web:
      exposure:
        include: info,prometheus
      base-path: /
      path-mapping:
        prometheus: metrics
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true