server:
  port: 8000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    net.brightlizard: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:31798/otus
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    initialization-mode: always
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
  sql:
    init:
      mode: always
      schema-locations: db/init.sql