apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-app.fullname" . }}
  labels:
    {{- include "otus-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otus-app.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-app.fullname" . }}-nodeport
  labels:
    {{- include "otus-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "otus-app.selectorLabels" . | nindent 4 }}
  type: NodePort
