apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-app.fullname" . }}
  labels:
    {{- include "otus-app.labels" . | nindent 4 }}
    app: {{ include "otus-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "otus-app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-app.fullname" . }}-nodeport
  labels:
    {{- include "otus-app.labels" . | nindent 4 }}
    app: {{ include "otus-app.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "otus-app.selectorLabels" . | nindent 4 }}