apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-internet-shop-app.fullname" . }}
  labels:
    {{- include "otus-internet-shop-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otus-internet-shop-app.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-internet-shop-app.fullname" . }}-nodeport
  labels:
    {{- include "otus-internet-shop-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "otus-internet-shop-app.selectorLabels" . | nindent 4 }}
