GET http://localhost:8000/health

###
GET http://localhost:8000/health/off

###
GET http://localhost:8000/health/on

###
#POST http://localhost:8000/user
POST http://arch.homework.helm/user
Content-Type: application/json

{
  "username": "bob",
  "firstName": "Bob",
  "lastName": "Uncle",
  "email": "somemail@mail.com",
  "phone": "+7(495)372-21-83"
}

###
#GET http://localhost:8000/user/1
GET http://arch.homework.helm/user/1
Content-Type: application/json

###
#PUT http://localhost:8000/user/1
PUT http://arch.homework.helm/user/1
Content-Type: application/json

{
  "username": "bob2",
  "firstName": "Bob2",
  "lastName": "Uncle2",
  "email": "somemail@mail.com",
  "phone": "+7(495)372-21-83"
}

###
#DELETE http://localhost:8000/user/2
DELETE http://arch.homework.helm/user/2
Content-Type: application/json

###
GET http://localhost:8000/actuator

###
GET http://localhost:8000/actuator/health

###
GET http://localhost:8000/metrics

###
GET http://localhost:8000/echo

###
GET http://localhost:8000/proxy?url=http://localhost:8000/echo
X-Test: Foo2